### ISSUE TITLE
Require cycle warnings

### ISSUE THREAD

**Issue by MohamadKh75** [HosseinShabani/react-native-modern-datepicker#10]
There are several require cycle warnings.
Shall I create a PR to resolve them by importing directly from the file? (as a temporary solution)
Or we can just use `YellowBox.ignoreWarnings(['Require cycle: '])`

**Comment by hiradary** [comment]
This will be reviewed ASAP. Thanks for submitting this issue!

**Comment by HosseinShabani** [comment]
This issue resolved

**Comment by ShuKTan** [comment]
still having same issue
