### ISSUE TITLE
How to select a predefined date when datepicker is opened ?

### ISSUE THREAD

**Issue by franferns** [HosseinShabani/react-native-modern-datepicker#113]
**Describe the bug**
How do i select a predefined date when the datepicker is opened ?

**To Reproduce**
1. Go to [react-native-modern-datepicker](https://snack.expo.dev/@francis25/date-sample)
2. A selected props is set to 14-09-2022 
3. When the date picker is shown the set date in the selected prop is not highlighted or selected same happens when set with the current prop too.

**Expected behavior**
Set a prop a date value to show date selected when the datepicker is shown 

**Screenshots**
https://snack.expo.dev/@francis25/date-sample

**Desktop (please complete the following information):**
 - OS: Android 11

**Comment by Ahmed-Imam** [comment]
any updates on this ? @franferns where u able to solve this ?

**Comment by franferns** [comment]
No could not find any solution for this

**Comment by franferns** [comment]
> any updates on this ? @franferns where u able to solve this ?

 @Ahmed-Imam I tried this one https://www.npmjs.com/package/@react-native-community/datetimepicker . May be this could be help.
