### ISSUE TITLE
Failed to compile

### ISSUE THREAD

**Issue by mahdibarati** [HosseinShabani/react-native-modern-datepicker#12]
./node_modules/react-native-modern-datepicker/src/datePicker/DatePicker.js
SyntaxError: \react-native-modern-datepicker\src\datePicker\DatePicker.js: Unexpected token (88:4)

**Comment by HosseinShabani** [comment]
@mahdibarati What is your react native version?

**Comment by mahdibarati** [comment]
"react-native": "0.58.1"

**Comment by HosseinShabani** [comment]
@mahdibarati This package uses React hooks. Make sure you're running react-native >= 0.59.0 version.
