### ISSUE TITLE
قابلیت تغییر رنگ روزها و غیر فعال کردن روزهای خاص

### ISSUE THREAD

**Issue by zahraerfani** [HosseinShabani/react-native-modern-datepicker#13]
سلام وقتتون بخیر
امکانش هست بتونیم روزهایی انتخاب کنیم و رنگ اون روزها تغییر کنه و یا روزهایی غیرفعال کنیم؟

**Comment by HosseinShabani** [comment]
سلام @zahraerfani 
روز میتونید انتخاب کنید و رنگشون متفاوته ولی چند روز امکانش نیست ، و روز های غیرفعال هم در ورژن بعدی اضافه میشه حتما
