### ISSUE TITLE
Wrong behavior in RTL mode

### ISSUE THREAD

**Issue by cybercoder** [HosseinShabani/react-native-modern-datepicker#15]
When the APP is in RTL mode, everything is reverse but can ignore,
The time picker will shows . wrong labels and selects wrong values in RTL mode.

**Comment by art1373** [comment]
I have this issue too. If I could I would do a pr and add isRTL boolean so that it reverse the rows and columns

**Comment by HosseinShabani** [comment]
Fix this issue in 1.0.0-beta.7 version . (and add reverse props for more customize)
