### ISSUE TITLE
Calendar direction is opposite.

### ISSUE THREAD

**Issue by peeyush-sahu** [HosseinShabani/react-native-modern-datepicker#23]
I think calendar direction is RTL by default. How to change that direction.

**Comment by HosseinShabani** [comment]
Direction depends on language , in Gregorian mode is LTR and we have reverse props for this topic

**Comment by peeyush-sahu** [comment]
> Direction depends on language , in Gregorian mode is LTR and we have reverse props for this topic

No, I am talking about the direction of previous and next. For Example: The current month is `May` and to go to next month i.e. June the arrow should be on right side as per LTR but it is on left side. Look at below image.
![IMG_5082](https://user-images.githubusercontent.com/14846708/82058086-e6127a00-96e1-11ea-87cc-23dfcf7d530b.jpg)

**Comment by peeyush-sahu** [comment]
Why you closed the issue. First resolve it. I am creating new issue.
