### ISSUE TITLE
Sometimes return wrong date

### ISSUE THREAD

**Issue by Sina-HZ** [HosseinShabani/react-native-modern-datepicker#30]
hi,
in calendar mode and jalaali dates type, the selected date is 1367/01/22 but it return 1366/12/22.

**Comment by moein7** [comment]
@Sina-HZ exactly i have this problem with this date picker. it is so strange.I accidently found this issue. any idea can help.

**Comment by HosseinShabani** [comment]
@moein7 @Sina-HZ you can update package to last version , fix in this version.
