### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by SaeedZhiany** [HosseinShabani/react-native-modern-datepicker#6]
Thank you for this library,

Have you any plan to add typescript support for it in the near future?

**Comment by HosseinShabani** [comment]
@SaeedZhiany That's a great idea. Will be added soon.

**Comment by SaeedZhiany** [comment]
Thanks, I suggest keep this issue open and close it by merging a PR.
you can close automatically this issue by writing `Fixes #6` in your PR's description.

**Comment by chrise86** [comment]
@SaeedZhiany any developments on the typescript support?

**Comment by SaeedZhiany** [comment]
> @SaeedZhiany any developments on the typescript support?

@chrise86 it's not my repository and I'm not using it in my projects, I created my own date picker that fit for my projects requirements, however it seems there is no typescript support by @HosseinShabani after 2 years. Maybe he had some update note on this thread.

**Comment by chrise86** [comment]
> > @SaeedZhiany any developments on the typescript support?
> 
> @chrise86 it's not my repository and I'm not using it in my projects, I created my own date picker that fit for my projects requirements, however it seems there is no typescript support by @HosseinShabani after 2 years. Maybe he had some update note on this thread.

Oh my bad, sorry, I must have selected the wrong username in the drop down 🤦‍♂️ I did indeed mean to tag @HosseinShabani
