### ISSUE TITLE
Support Second picker

### ISSUE THREAD

**Issue by SaeedZhiany** [HosseinShabani/react-native-modern-datepicker#7]
it would be a great feature if you add a second picker in time picker section.

**Comment by HosseinShabani** [comment]
@SaeedZhiany I don't get it. Would you please explain more?

**Comment by SaeedZhiany** [comment]
From your website, I saw that the user only can select Hour and Minute section of time.
I suggest you to add a feature that user can select Second section as well.

**IOS time picker example**

![image](https://user-images.githubusercontent.com/13766432/66480927-92d1ac80-eaac-11e9-8130-ec30ac231b8d.png)

**Android time picker example**
![image](https://user-images.githubusercontent.com/13766432/66481206-391db200-eaad-11e9-90bb-d9df7b092420.png)

**Comment by HosseinShabani** [comment]
I'll add this feature in the .next release
