### ISSUE TITLE
React Native < 59 not supported

### ISSUE THREAD

**Issue by MohamadKh75** [HosseinShabani/react-native-modern-datepicker#9]
As we can see [here](https://github.com/HosseinShabani/react-native-modern-datepicker/blob/master/src/datePicker/DatePicker.js#L1), this library based on hooks which have been implemented in RN 0.59 ([Link](http://facebook.github.io/react-native/blog/2019/03/12/releasing-react-native-059)) so we should rewrite it OR add a note to ReadMe.

**Comment by HosseinShabani** [comment]
Thanks for your suggestion! It'd be a good idea to have this. However, I'm not planning to add < 59 support for now. It's already been mentioned in the website.
